---
- name: Install curl for NodeSource setup
  apt:
    name: curl
    state: present
    update_cache: yes

- name: Add NodeSource GPG key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Add NodeSource repository for Node.js 20.x
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_20.x {{ ansible_distribution_release }} main"
    state: present

- name: Install Node.js 20.x (required for Claude Code)
  apt:
    name: nodejs
    state: present
    update_cache: yes

- name: Install Claude Code globally
  npm:
    name: "{{ claude_code_package }}"
    global: "{{ claude_code_global_install }}"
    state: present

- name: Verify Claude Code installation
  command: claude --version
  register: claude_version
  changed_when: false
  failed_when: claude_version.rc != 0

- name: Display Claude Code version
  debug:
    msg: "Claude Code installed successfully: {{ claude_version.stdout }}"