---
- name: Install curl and ca-certificates
  apt:
    name:
      - curl
      - ca-certificates
      - gnupg
    state: present
    update_cache: yes

- name: Create keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download and add NodeSource GPG key
  shell: |
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
  args:
    creates: /etc/apt/keyrings/nodesource.gpg

- name: Add NodeSource repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main"
    state: present
    filename: nodesource

- name: Install Node.js 20.x (required for Claude Code)
  apt:
    name: nodejs
    state: present
    update_cache: yes

- name: Install Claude Code globally
  npm:
    name: "{{ claude_code_package }}"
    global: "{{ claude_code_global_install }}"
    state: present

- name: Verify Claude Code installation
  command: claude --version
  register: claude_version
  changed_when: false
  failed_when: claude_version.rc != 0

- name: Display Claude Code version
  debug:
    msg: "Claude Code installed successfully: {{ claude_version.stdout }}"